name: Node.js CI
on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        node: [14.18.0, 14, 16.0.0, 16]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          # Node 14 is not available on macos anymore
          - os: macos-latest
            node-version: 14
          - os: macos-latest
            node-version: 14.18.0
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
